---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - helm.fluxcd.io
  resources:
  - helmreleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - helm.fluxcd.io
  resources:
  - helmreleases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - source.fluxcd.io
  resources:
  - helmcharts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - source.fluxcd.io
  resources:
  - helmcharts/status
  verbs:
  - get
